### ISSUE TITLE
行研

### ISSUE THREAD

**Issue by Jerry-Ziyu-Chai** [l-O-O-l/TTS-action#49]
SIA
1). Summer情况：
i. 今年基本全部上岸二级买
2). 二级买：
i. 大量的数据、研究框架、交流与写报告、投资能力
ii. 2-3份 研究报告，独立思考、逻辑能力。
iii. 最近在读什么书，投资看法
iv. 行业优点：
a) 陡峭曲线
b) 个人品牌
c) 工作量相对低
v. 缺点：
a) 自我驱动，混不了
b) 结果导向
3). 求职路径：
i. T-1年 3-6月份，笔试，面试
ii. T-1年的 6-10月 summer
iii. 毕业 0-6年 初-高级研究员
4). 招人标准：
i. 二级市场/价值投资研究经历
ii. 勤奋/草根，注意细节
iii. 独立思考、逻辑性强（金字塔原理）
5). 好奇心：广泛阅读、想法多
6). 隐形优势：
i. 清华本硕、理工科复合背景、男生（不一定）
7). 市场情况：
i. 基金招人现在在扩张后半期
ii. 暑期留用率 20-30%；暑期2-3份
iii. 研究员覆盖量平均下降：之前是一个行业一个坑，现在研究员扩招，有些赛道需要更多人覆盖
iv. 分公司人数信息：
8). 竞争格局：
i. 研一 买方实习
ii. 汇丰，二级见长
iii. 复旦政协 投资聚义厅（）
iv. 五道口、高金都有二级协会
v. 面试需要干货积累较多
9). Conclusion：
i. 2022年预计较难增加
ii. 招人标准逐年提高，仅有big name/丰富实习/面试技巧高不一定能拿到return
10). 实际上，放出offer的数量，远大于招标人数。（最后一名只有5分）
11). How to get the offer:
12). 学习内容
i. 目标：调整对三张表的预测参数
ii. 行业空间增长、市占率提升、净利润增长
iii. 产业链及产业链地位、格局。
iv. 竞争模式
v. 核心差异
vi. 国际对标
vii. 管理层研究：基本情况、业务
13). 学习内容：股票投资、资产配置、如何练级
i. 基本面与投资的关系
ii. 研究是研究，投资是投资。不做研究和做80%研究是没啥区别的
iii. A/B/C哪个更好，基于什么指标？ 行业比较。
iv. 最底层的逻辑是怎么样的，博弈预期？研究问题的框架，输入系统，
v. 强和弱，是跟谁比？
vi. 运费，大宗商品。我国很多出口型制造业的cost在不断提升，α，大部分出口企业没办法涨价。 宏观趋势---微观经营
14). 存在问题和本质问题
i. 什么是？好赛道、好公司长什么样
a) 筛选指标
b) 指标是否变化：
c) Fact& proxy: 确定性。对一个事情确定性的分析，是大众认识不足还是就不太确定？
a) 军工：不确定性资产。但其实是确定性最高的资产。计划经济（TO G），底层稳定。 所谓市场上的不确定性高，是对他不认知不了解。 不确定性高可能是自己认知的问题
ii. 像三一---是不是有一个优秀的公司。想三一的优秀的因素是不是成功的因素，这个因素是不是在这个行业优秀，以及之前和之后是否有区别
iii. 海天味业，全国市占率， 单品价格都很好，现金流好。涨价涨不动，涨价会影响销量。以前是供应商渠道，现在是社区团购。 茅台，渠道会维持以前的渠道，什么时候涨价/降价？
iv. 产品力>渠道力
15). 会计、经济学原理
i. 会计知识可以复用。懂石油不一定懂TMT，但是会计可以复用。31个行业都可以复用
ii. 经济学原理：中微，提供sense（驱动力）博弈论、均衡理论
iii. 三张表配平，勾稽关系；经过产业对报表分析；合并报表
16). 为什么对消费品不分析供应链？
17). 面试纪律：
i. 面试：ppt/word 5分钟交流？
ii. 期末要交一篇报告，寒假一篇报告（和实习有帮助）。
iii. 末尾淘汰（淘汰很多人）；
18). 不要自我神话，自信，否认“天才论”
19). 量、勤奋度、悟性
20). 宗旨：团结共赢（why sia， it’s a good point to say）
21). 书籍：
i. 投资中最简单的事，投资中不简单的事，破浪者——白金分析师中的电子行业十年；邓晓峰老师的书推荐。冯柳，投资是什么事儿（索罗斯）。金融炼金术
ii. 历史/社会/自顶向下（互联网底层架构）
iii. 好好学习/学会提问/高效能人士的七个习惯/金字塔原理
a) 15个点是怎么连接起来的，为什么这么连接
22). 其他
i. 自己的竞争对手是谁？金融本？电子本？
ii. Return offer 框架的完整性，易学难精。To 大b to小b，什么可以提价，什么不可以。购买频次，单品价值量。
iii. 很多课能翘就翘，成绩没那么不重要
iv. 腾讯云。 讯飞H1
v. 越接近于商业模式/越接近于技术难度
vi. 喜欢/不喜欢；擅长/不擅长。怎么去思考。
vii. 喜欢看书，好奇心--- 摄取外界信息的途径
23). 职业规划？

**Comment by l-O-O-l** [comment]
本項目 issue 有專門的格式 ， 中文開始需要以 `TTS-CN: ` 開始， 且只支持中文，不支持數字英文等。
